spring.application.name=mobile-wallet-disbursement-svc

# 1. Enable Spring Boot 3.2+ Virtual Threads
spring.threads.virtual.enabled=true

# 2. Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=update
spring.liquibase.drop-first=true
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.sql
spring.jpa.show-sql=false

# 3. Custom Logging Pattern: [TraceID] [ThreadName] LEVEL - Message
logging.pattern.console=[%X{traceId}] [%thread] %-5level %logger{36} - %msg%n
